version: '3.1'
services:
  mysql:
    container_name: arobank_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test_pass # TODO: Change this
      MYSQL_USER: test
      MYSQL_PASS: pass
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  my-datavolume:
